# Generated by Django 5.2 on 2025-04-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
